.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Anzeigen/AnzeigeSteuerung.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Anzeigen/AnzeigeSteuerung.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnzeigeSteuerung\fP"
.br
.RI "This class implements the basic functions to create displays that distinguish between three value ranges: normal (white), abnormal (orange), and critical (red)\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
