.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte Directory Reference" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAnzeigen\fP"
.br
.ti -1c
.RI "directory \fBClipboards\fP"
.br
.ti -1c
.RI "directory \fBGazeGuiding\fP"
.br
.ti -1c
.RI "directory \fBGazeGuidingPath\fP"
.br
.ti -1c
.RI "directory \fBNPPClient\fP"
.br
.ti -1c
.RI "directory \fBRegler\fP"
.br
.ti -1c
.RI "directory \fBshader\fP"
.br
.ti -1c
.RI "directory \fBStateMachine\fP"
.br
.ti -1c
.RI "directory \fBUI\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAusfallAnzeige\&.cs\fP"
.br
.ti -1c
.RI "file \fBAusfallAnzeigenManager\&.cs\fP"
.br
.ti -1c
.RI "file \fBdisableDistractions\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalConfig\&.cs\fP"
.br
.ti -1c
.RI "file \fBReglerControl\&.cs\fP"
.br
.ti -1c
.RI "file \fBTuerRESET\&.cs\fP"
.br
.ti -1c
.RI "file \fBWelcomeScreen\&.cs\fP"
.br
.in -1c
