.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Clipboards/ClipboardInitialStateScenario.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Clipboards/ClipboardInitialStateScenario.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClipboardInitialStateShutdown\fP"
.br
.RI "This class implements logic to trigger the startup scenario of the \fBNPPClient\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
