.TH "CollisionHandler" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollisionHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnTriggerEnter\fP (Collider other)"
.br
.ti -1c
.RI "void \fBOnTriggerExit\fP (Collider other)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CollisionHandler\&.OnTriggerEnter (Collider other)\fR [private]\fP"

.SS "void CollisionHandler\&.OnTriggerExit (Collider other)\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
