.TH "CondenserState" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CondenserState \- This class is used to store the state of the condenser component\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBpressure\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIpressure\fP stores the pressure inside the condenser tank
.RE
.PP
"
.ti -1c
.RI "float \fBwaterLevel\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIwaterLevel\fP stores the water level inside the condenser tank
.RE
.PP
"
.ti -1c
.RI "bool \fBoperational\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIoperational\fP tracks whether the condenser tank is operational 
.RE
.PP
"
.in -1c
.SH "Detailed Description"
.PP 
This class is used to store the state of the condenser component\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool CondenserState\&.operational"

.PP

.PP
\fBParameters\fP
.RS 4
\fIoperational\fP tracks whether the condenser tank is operational 
.RE
.PP

.SS "float CondenserState\&.pressure"

.PP

.PP
\fBParameters\fP
.RS 4
\fIpressure\fP stores the pressure inside the condenser tank
.RE
.PP

.SS "float CondenserState\&.waterLevel"

.PP

.PP
\fBParameters\fP
.RS 4
\fIwaterLevel\fP stores the water level inside the condenser tank
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
