.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Regler/LightRegler.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Regler/LightRegler.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLightRegler\fP"
.br
.RI "This class implements a small lamp that is attachable to rotary switches\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
