.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/NPPClient/NPPClient.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/NPPClient/NPPClient.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNPPClient\fP"
.br
.RI "This class implements logic for connecting to the REST Server running the simulation and fetching the current state of the simulation's components\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBRandom\fP = UnityEngine\&.Random"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBRandom\fP = UnityEngine\&.Random"

.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
