.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/NPPClient/NPPReactorState.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/NPPClient/NPPReactorState.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNPPReactorState\fP"
.br
.RI "This class is used to store the state of the simulation\&. "
.ti -1c
.RI "class \fBCondenserState\fP"
.br
.RI "This class is used to store the state of the condenser component\&. "
.ti -1c
.RI "class \fBGeneratorState\fP"
.br
.RI "This class is used to store the state of the generator component\&. "
.ti -1c
.RI "class \fBReactorState\fP"
.br
.RI "This class is used to store the state of the reactor component\&. "
.ti -1c
.RI "class \fBPumpState\fP"
.br
.RI "This class is used to store the state of a pump component\&. "
.ti -1c
.RI "class \fBValveState\fP"
.br
.RI "This class is used to store the state of a valve component\&. "
.ti -1c
.RI "class \fBComponentHealth\fP"
.br
.RI "This class is used to store the state of all components, see \fBComponentState\fP\&. "
.ti -1c
.RI "class \fBComponentState\fP"
.br
.RI "This class is used to store the state of a component\&. "
.ti -1c
.RI "class \fBSystemStatus\fP"
.br
.RI "This class is used to store the state of the simulation\&. "
.ti -1c
.RI "class \fBErrorState\fP"
.br
.RI "This class is used to store error states\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
