.TH "PumpState" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PumpState \- This class is used to store the state of a pump component\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIname\fP stores the name of a pump
.RE
.PP
"
.ti -1c
.RI "bool \fBblown\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIblown\fP tracks whether the pump is blown
.RE
.PP
"
.ti -1c
.RI "float \fBrpm\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIrpm\fP stores the current RPM of a pump
.RE
.PP
"
.ti -1c
.RI "float \fBsetRpm\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIsetRpm\fP stores the set RPM of a pump
.RE
.PP
"
.ti -1c
.RI "float \fBmaxRpm\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fImaxRpm\fP stores the maximum RPM of a pump
.RE
.PP
"
.ti -1c
.RI "bool \fBoperational\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIoperational\fP tracks whether a pump is operational
.RE
.PP
"
.in -1c
.SH "Detailed Description"
.PP 
This class is used to store the state of a pump component\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool PumpState\&.blown"

.PP

.PP
\fBParameters\fP
.RS 4
\fIblown\fP tracks whether the pump is blown
.RE
.PP

.SS "float PumpState\&.maxRpm"

.PP

.PP
\fBParameters\fP
.RS 4
\fImaxRpm\fP stores the maximum RPM of a pump
.RE
.PP

.SS "string PumpState\&.name"

.PP

.PP
\fBParameters\fP
.RS 4
\fIname\fP stores the name of a pump
.RE
.PP

.SS "bool PumpState\&.operational"

.PP

.PP
\fBParameters\fP
.RS 4
\fIoperational\fP tracks whether a pump is operational
.RE
.PP

.SS "float PumpState\&.rpm"

.PP

.PP
\fBParameters\fP
.RS 4
\fIrpm\fP stores the current RPM of a pump
.RE
.PP

.SS "float PumpState\&.setRpm"

.PP

.PP
\fBParameters\fP
.RS 4
\fIsetRpm\fP stores the set RPM of a pump
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
