.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/UI/Rotate3DArrow.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/UI/Rotate3DArrow.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRotate3DArrow\fP"
.br
.RI "This class implements a continuously rotating 3D arrow as a visual cue indicating the direction in which the player is supposed to turn an exact switch\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
