.TH "s3003" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s3003
.SH SYNOPSIS
.br
.PP
.PP
Inherits StateMachineBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnStateEnter\fP (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"
.br
.ti -1c
.RI "override void \fBOnStateUpdate\fP (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"
.br
.ti -1c
.RI "override void \fBOnStateExit\fP (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtarget\fP"
.br
.ti -1c
.RI "GameObject \fBtarget2\fP"
.br
.ti -1c
.RI "\fBGazeGuidingPathPlayer\fP \fBgazeGuidingPathPlayer\fP"
.br
.ti -1c
.RI "\fBGazeGuidingPathPlayerSecondPath\fP \fBgazeGuidingPathPlayer2\fP"
.br
.ti -1c
.RI "\fBNPPReactorState\fP \fBsimulation\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void s3003\&.OnStateEnter (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"

.SS "override void s3003\&.OnStateExit (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"

.SS "override void s3003\&.OnStateUpdate (Animator animator, AnimatorStateInfo stateInfo, int layerIndex)"

.SH "Member Data Documentation"
.PP 
.SS "\fBGazeGuidingPathPlayer\fP s3003\&.gazeGuidingPathPlayer\fR [private]\fP"

.SS "\fBGazeGuidingPathPlayerSecondPath\fP s3003\&.gazeGuidingPathPlayer2\fR [private]\fP"

.SS "\fBNPPReactorState\fP s3003\&.simulation\fR [private]\fP"

.SS "GameObject s3003\&.target\fR [private]\fP"

.SS "GameObject s3003\&.target2\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
