.TH "SystemStatus" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SystemStatus \- This class is used to store the state of the simulation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DateTime \fBgetDate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBrunningSince\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIrunningSince\fP stores the time the simulation has been running
.RE
.PP
"
.ti -1c
.RI "bool \fBrunning\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIrunning\fP tracks whether the simulation is running
.RE
.PP
"
.in -1c
.SH "Detailed Description"
.PP 
This class is used to store the state of the simulation\&. 
.SH "Member Function Documentation"
.PP 
.SS "DateTime SystemStatus\&.getDate ()"

.SH "Member Data Documentation"
.PP 
.SS "bool SystemStatus\&.running"

.PP

.PP
\fBParameters\fP
.RS 4
\fIrunning\fP tracks whether the simulation is running
.RE
.PP
summary> Returns a DateTime object from the runningSince string 
.SS "string SystemStatus\&.runningSince"

.PP

.PP
\fBParameters\fP
.RS 4
\fIrunningSince\fP stores the time the simulation has been running
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
