.TH "ValveState" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValveState \- This class is used to store the state of a valve component\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIname\fP stores the name of a valve
.RE
.PP
"
.ti -1c
.RI "bool \fBblown\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIblown\fP tracks whether a valve is blown
.RE
.PP
"
.ti -1c
.RI "bool \fBstatus\fP"
.br
.RI "
.PP
\fBParameters\fP
.RS 4
\fIstatus\fP tracks whether a valve is open
.RE
.PP
"
.in -1c
.SH "Detailed Description"
.PP 
This class is used to store the state of a valve component\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool ValveState\&.blown"

.PP

.PP
\fBParameters\fP
.RS 4
\fIblown\fP tracks whether a valve is blown
.RE
.PP

.SS "string ValveState\&.name"

.PP

.PP
\fBParameters\fP
.RS 4
\fIname\fP stores the name of a valve
.RE
.PP

.SS "bool ValveState\&.status"

.PP

.PP
\fBParameters\fP
.RS 4
\fIstatus\fP tracks whether a valve is open
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
