.TH "C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Regler/WV1.cs" 3 "Version 0.1" "NPP VR Simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/playground/Unity/Softwareprojekt_VR-Reaktor-Leitwarte/Assets/Skripte/Regler/WV1.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWV1\fP"
.br
.RI "This class is used to control water valve 1 in an NPP simulation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NPP VR Simulation from the source code\&.
